name: CI-CD-Pipeline-To-Yandex-Cloud

on:
  push:
    branches:
      - master

env:
  DEPLOY_PACKAGE_NAME: "my_cv_${{ github.sha }}.zip"
  HOST               : ${{ secrets.HOST }}
  USERNAME           : ${{ secrets.USERNAME }}
  KEY                : ${{ secrets.KEY}}

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v4

      - name: Unit tests execution
        run: echo "Unit Tests passed"

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host    : ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          KEY     : ${{ env.KEY }}
          target  : .
          source  : "/var/www/html"

      - name: Print happy message fro CI finish
        run: echo "CI Pipeline part Finished successfully"
